#!/bin/bash
### install

cache_devs=$1
backing_devs=$2

for dev in ${cache_devs} ${backing_devs}
do
    if [ ! -e "/dev/${dev}" ];then
        echo "Err: ${dev} not exist"
        exit 1
    fi
done

cache_devs=(${cache_devs// / })
backing_devs=(${backing_devs// / })
cache_dev_num=${#cache_devs[*]}
backing_dev_num=${#backing_devs[*]}
if [ "$cache_dev_num" -ne "$backing_dev_num" ];then
    echo "cache disk number not equal to backing disk number..."
    exit 1
fi

for ((i=0;i<$backing_dev_num;i++));do
    backing_dev=${backing_devs[$i]}
    cache_dev=${cache_devs[$i]}
    echo "Init bcache: $backing_dev -- $cache_dev"

    echo "wipe backing device $backing_dev ..."
    wipefs /dev/${backing_dev}
    wipefs -a /dev/${backing_dev}
    sleep 1

    # init every bcache dev
    echo "Init dev ${cache_dev} -- ${backing_dev}..."
    backing_dev_uuid=`make-bcache -B /dev/${backing_dev} --wipe-bcache | grep -i 'Set UUID:' | awk -F ':' '{print $2}'`
    backing_dev_uuid=`echo $backing_dev_uuid | sed -e 's/^ *//' -e 's/ *$//'`

    cache_dev_uuid=`make-bcache --bucket 512k -C /dev/${cache_dev} --wipe-bcache | grep -i 'Set UUID:' | awk -F ':' '{print $2}'`
    cache_dev_uuid=`echo $cache_dev_uuid | sed -e 's/^ *//' -e 's/ *$//'`

    # register
    echo "Register ${cache_dev} -- ${backing_dev} to bcache..."
    echo /dev/${cache_dev} > /sys/fs/bcache/register
    echo /dev/${backing_dev} > /sys/fs/bcache/register

    sleep 3

    # get the bcache dev name
    disk_uuid=`bcache-super-show /dev/${backing_dev} | grep 'dev.uuid' | awk '{print $2}'`
    bcache_dev=`ls -l /dev/bcache/by-uuid/${disk_uuid} | awk -F '->' '{print $2}' | xargs basename`

    # attach cache dev to backing dev
    echo ${cache_dev_uuid} > /sys/block/${bcache_dev}/bcache/attach

    # tunning
    echo writeback > /sys/block/${bcache_dev}/bcache/cache_mode
    echo 0 > /sys/block/${bcache_dev}/bcache/writeback_percent
    echo 10000 >/sys/block/${bcache_dev}/bcache/writeback_rate

    echo 0 > /sys/fs/bcache/${cache_dev_uuid}/congested_read_threshold_us
    echo 0 > /sys/fs/bcache/${cache_dev_uuid}/congested_write_threshold_us

    # open seq write cache
    # echo 0 > /sys/block/${bcache_dev}/bcache/sequential_cutoff

    # default: close seq write cache
    # echo 4M > /sys/block/${bcache_dev}/bcache/sequential_cutoff
done

