#!/bin/bash
sed -i 's/^GRUB_CMDLINE_LINUX="/GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 elevator=deadline numa=off /g' /etc/default/grub
sed -i 's/^GRUB_CMDLINE_LINUX="/GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 elevator=deadline numa=off /g' /etc/sysconfig/grub
grub2-mkconfig -o /boot/grub2/grub.cfg

INSTALL_TAG='xcloud install'
cat > /tmp/tuning.tmp <<EOF
# $INSTALL_TAG
# Use TCP syncookies when needed
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1800
net.ipv4.tcp_sack = 1
net.ipv4.tcp_timestamps = 1

#Enable TCP window scaling
net.ipv4.tcp_window_scaling = 1

#Increase TCP max buffer size
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216

#Increase Linux autotuning TCP buffer limits
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

#Increase number of ports available
net.ipv4.ip_local_port_range = 1024 65535

net.netfilter.nf_conntrack_max = 655350
net.netfilter.nf_conntrack_tcp_timeout_established = 7200

# ip forward
net.ipv4.ip_forward = 1

# swap
vm.swappiness=0
EOF
ret=`grep -P "^# $INSTALL_TAG" /etc/sysctl.conf`
if [ "" == "$ret" ];then
    cat /tmp/tuning.tmp >> /etc/sysctl.conf
    sysctl -p
fi
