#!/bin/bash
vip='172.16.92.30'
interface='ens160'

for i in {1..4};do
    mod=$(cat /etc/keepalived/state)
    ip -o addr show $interface | grep -q $vip/32;vip_state=$?
    sleep 15
done

compute_driver=$(openstack-config --get /etc/nova/nova.conf DEFAULT compute_driver)
if [[ $vip_state -ne 0 && $mode != 'master' ]]; then
    systemctl stop cloudkitty-processor openstack-ceilometer-alarm-evaluator openstack-ceilometer-central
    if [ "nova.virt.ironic.IronicDriver" == "$compute_driver" ];then
        systemctl stop openstack-ironic-api openstack-ironic-conductor
    fi
fi
