#!/bin/sh

if [ $# -ne 2 ]
then
        echo "Usage: $0 <server_list_file> <shell_file>"
        exit
fi

server_list_file=$1
cmd_file=$2
cmd_file_name=`basename $cmd_file`
remote_cmd_file='/tmp/'$cmd_file_name
node_list=`cat $server_list_file | grep -v '#' | grep -v grep`
echo 'remote cmd file is : '$remote_cmd_file

for node in $node_list; do
	continue
	echo 'ensure ssh tunel' > test_ssh_tunel
	scp test_ssh_tunel $node:/tmp/test_ssh_tunel
done

for node in $node_list; do
	echo "scp $cmd_file $node:$remote_cmd_file"
	scp $cmd_file $node:$remote_cmd_file
	if [ $? -ne 0 ]
	then
		echo "$node scp file fail[$?]"
		continue
	fi
	echo "ssh $node '$remote_cmd_file'"
	ssh $node "chmod 777 $remote_cmd_file"
	ssh $node "sh $remote_cmd_file"
	if [ $? -ne 0 ]
	then
		echo "$node exec $cmd_file fail[$?]"
		continue
	fi
done
