#!/bin/bash
while true; do echo -e 'HTTP/1.0 200 OK\r\n\r\n''{"status": "pass", "errMsg": "None"}' | nc -l 8099 ; done
# while true; do echo -e 'HTTP/1.0 200 OK\r\n\r\n''{"status": "fail", "errMsg": "None"}' | nc -l 8099 ; done
